<?php

/**
 * @file
 * Patternkit Media Library Support.
 */

use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function patternkit_media_library_form_layout_builder_configure_block_alter(&$form, $form_state) {
  if (!empty($form['settings']['configuration']['#attached']['drupalSettings']['patternkitEditor'])) {
    $form_attached = $form['settings']['configuration']['#attached'];
    $form_attached['drupalSettings']['patternkitEditor']['imageUrl'] = Url::fromRoute('patternkit.media_library')
      ->toString();
    array_unshift($form_attached['library'], 'patternkit_media_library/patternkit.jsoneditor.media_library');
    $form['settings']['configuration']['#attached'] = $form_attached;
  }
}
